### ISSUE TITLE
AsciiDoc javadocs are no longer rendered in IntelliJ IDEA

### ISSUE THREAD

**Issue by mederly** [ahus1/asciidoclet-intellij-plugin#2]
Hello.

The viewing of rendered AsciiDoc Java documentation no longer works in IntelliJ IDEA. Some releases ago (I don't remember exactly, but somewhere in 2021) the Rendered View (Ctrl+Alt+Q) stopped recognizing AsciiDoc, and currently in 2022.1.1 even standard documentation view (Ctrl+Q) no longer works.

---

As for the latter issue, I have found that the problem is in the change of HTML generated by IDEA. Originally, it was like this (formatting added by me):

```<html>
    <head>
        <base href="...">
    </head>
    <body>
        <div class='definition'>
            ...
        </div>
        <div class='content'>
            ...  
        </div>
        <table class='sections'>
            <p>
        </table>
```

but in 2022.1.1 it is like:

```
<html>
    <head>
        <base href="...">
    </head>
    <body>
        <div class='definition'>
           ...
        </div>
        <div class='content'>
           ...  
        </div>
        <table class='sections'>
            <p>
        </table>
        <div class="bottom">
            ...
        </div>
```

The current `touchUp` code looks for the last `</div>` to find the javadoc in which it tries to detect presence of HTML tags. And obviously it sees the `<p>` there (as it's always between the start of the javadoc and the final `</div>`).

This can be fixed by changing the line 34 of `AsciidocletJavaDocInfoGenerator` to:

```
  public static final String END = "</div><table class='sections'>";
```
(although I am not sure if this is general enough - but at least in my case it works)

**EDIT**: I just have found that here is a PR that addresses this "div" issue! I missed it somehow.

---

However, I am not able to diagnose nor fix the first mentioned issue: Displaying AsciiDoc in the Rendered View (Ctrl+Alt+Q). It was really nice and useful in 2020.* versions of IDEA and I miss it very much.

Thank you!

AsciiDoc Plugin Version: 0.37.17
Asciidoclet Plugin Version: 0.1.2
IDE Name and Version: IntelliJ IDEA 2022.1.1 (Ultimate Edition), build #IU-221.5591.52, built on May 10, 2022

**Comment by mederly** [comment]
As for the Rendered View, I am afraid the problem is right in IntelliJ IDEA code.

This commit: https://github.com/JetBrains/intellij-community/commit/7a19bcbefdcf8d7ccfc0ebf40fc36f1bf5f6b05f#diff-308aca2d72e4175ea23be947ab87769d8481ad98cac86cfd73cd755172aea008L231-R241

has replaced the correct `JavaDocInfoGeneratorFactory.create` call (that correctly looks for `JavaDocInfoGeneratorFactory` service implementation, i.e. `AsciidocletJavaDocInfoGeneratorFactory`) by incorrect `JavaDocInfoGeneratorFactory.getBuilder` that is hard-coded to instantiate `JavaDocInfoGeneratorBuilder` class.

I am afraid this cannot be fixed in this plugin, without changing IntelliJ IDEA code.

**Comment by mederly** [comment]
https://youtrack.jetbrains.com/issue/IDEA-294263

**Comment by ahus1** [comment]
Thanks for reporting this problem upstream in the JetBrains tracker. Unfortunately I didn't see this issue until now as I misconfigured my notification settings. 

I see that the upstream issue is fixed from 2022.2 according to YouTrack. I also tested it locally it and it seem to work, so I close this issue. Please let me know if I missed something.

**Comment by mederly** [comment]
Hello, unfortunately, the fix in IntelliJ IDEA is only a prerequisite for the Rendered View to work. I didn't have the time to use their fix to do the appropriate changes in the Asciidoclet plugin.

The rendered view still does not work, see e.g.

**Traditional view (correct)**

![image](https://user-images.githubusercontent.com/5798500/201998859-23376bd4-9be0-4e12-9729-98a6d148ef5f.png)

**Rendered view (incorrect)**

![image](https://user-images.githubusercontent.com/5798500/201998991-6b0c5519-bb3f-4c61-9793-9f37b87c6785.png)

**Comment by ahus1** [comment]
Thank you for adding the screenshot, I now understand what you meant in your first comment. 

The changes upstream weren't sufficient as the constructor of the class is still not public. I managed to leverage a different API, and now this should work.

Please give pre-release 0.1.4 a try. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/ahus1/asciidoclet-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `asciidoclet-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by mederly** [comment]
It works great now. Thank you very much!
